In [5]:
import numpy as np

In [3]:
a=np.arange(10)
a.dtype

dtype('int32')

In [4]:
a=np.arange(10, dtype='float64') #Implicitly it convert to floating data type
a

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [13]:
a=np.zeros((3,3))
print(a)
a.dtype

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


dtype('float64')

In [14]:
a=np.ones((3,3))
print(a)
a.dtype

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


dtype('float64')

In [18]:
d=np.array([1+2j,2+3j]) #complex datatype
print(d.dtype)
d.dtype

complex128


dtype('complex128')

In [17]:
b=np.array([True,False,True,False]) #Boolean data type
print(b.dtype)

bool


In [19]:
s=np.array(["Shiva","Ram","Laxman","Hanuman"])
s.dtype

dtype('<U7')

In [ ]:
#Each built in data type has character code that uniquely identifies it

In [ ]:
#Indexing and slicing


In [20]:
a=np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [21]:
print(a[5])

5


In [23]:
a=np.diag([1,2,3])
a[2,2]

3

In [24]:
a[2,1]=5 #assigning value
a

array([[1, 0, 0],
       [0, 2, 0],
       [0, 5, 3]])

In [16]:
#slicing
a=np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [17]:
a[1:8:2] # start index,end index,step siz


array([1, 3, 5, 7])

In [18]:
a[5:] #Start with 5th index and going till end default step size 1

array([5, 6, 7, 8, 9])

In [19]:
a[:7]

array([0, 1, 2, 3, 4, 5, 6])

In [20]:
a[:]

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [21]:
a[::2]

array([0, 2, 4, 6, 8])

In [22]:
a[-1]

9

In [24]:
a[5:] =10 #From 5 index to 5th index got value 10 for all indexes
a

array([ 0,  1,  2,  3,  4, 10, 10, 10, 10, 10])

In [25]:
b=np.arange(5)
b

array([0, 1, 2, 3, 4])

In [27]:
a[5:]=b[::-1] #assiging value of b is in reverse and then from 5th index it will assign corresponing position
a

array([0, 1, 2, 3, 4, 4, 3, 2, 1, 0])

In [ ]:
#Copies and views 
#When modifiying the view, the original arrray is modified as well

In [28]:
a=np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [29]:
b=a[::2] #a's element we assign in to b
b


array([0, 2, 4, 6, 8])

In [30]:
np.shares_memory(a,b) 

True

In [31]:
b[0]=10
b

array([10,  2,  4,  6,  8])

In [33]:
a # Eventhough we modified b,Here a value also updated because a and b sharessame memory

array([10,  1,  2,  3,  4,  5,  6,  7,  8,  9])

In [34]:
a=np.arange(10)
c=a[::2].copy() #Force a copy
c

array([0, 2, 4, 6, 8])

In [35]:
np.shares_memory(a,c) #False because they are not share same memory

False

In [36]:
c[0]=10
c

array([10,  2,  4,  6,  8])

In [37]:
a #Here not change because they are not share same memory

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [38]:
#Fancy Indexing
#Using Boolean Mask
a=np.random.randint(0,20,15) #It will generate 15 random element between 0 to 20
a

array([13,  2,  9, 15,  3, 19, 10,  8,  8,  2, 18,  2, 15,  9,  6])

In [39]:
mask =(a % 2 ==0)

In [40]:
extract_from_a=a[mask]
extract_from_a

array([ 2, 10,  8,  8,  2, 18,  2,  6])

In [ ]:
#Indexing with mask

In [41]:
a[mask]=-1
a

array([13, -1,  9, 15,  3, 19, -1, -1, -1, -1, -1, -1, 15,  9, -1])

In [43]:
a=np.arange(0,100,10)
a

array([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [46]:
a[[2,3,2,4,2]] #2-20  3-30 2-40 Indexing can be done with an array of intergers,where the same index is repeated several times


array([20, 30, 20, 40, 20])

In [47]:
#New values can be assigned 
a[[9,7]]=500  # at 9th and 7 th index 500 will be assigned
a

array([  0,  10,  20,  30,  40,  50,  60, 500,  80, 500])