In [15]:
import numpy as np
import pandas as pd

ModuleNotFoundError: No module named 'pandas'

In [12]:
data=np.loadtxt("populations1.txt")

In [13]:
data

array([[ 1900., 30000.,  4000., 48300.],
       [ 1901., 47200.,  6100., 48200.],
       [ 1902., 70200.,  9800., 41500.],
       [ 1903., 77400., 35200., 38200.],
       [ 1904., 36300., 59400., 40600.],
       [ 1905., 20600., 41700., 39800.],
       [ 1906., 18100., 19000., 38600.],
       [ 1907., 21400., 13000., 42300.],
       [ 1908., 22000.,  8300., 44500.],
       [ 1909., 25400.,  9100., 42100.],
       [ 1910., 27100.,  7400., 46000.],
       [ 1911., 40300.,  8000., 46800.],
       [ 1912., 57000., 12300., 43800.],
       [ 1913., 76600., 19500., 40900.],
       [ 1914., 52300., 45700., 39400.],
       [ 1915., 19500., 51100., 39000.],
       [ 1916., 11200., 29700., 36700.],
       [ 1917.,  7600., 15800., 41800.],
       [ 1918., 14600.,  9700., 43300.],
       [ 1919., 16200., 10100., 41300.],
       [ 1920., 24700.,  8600., 47300.]])

In [16]:
data

array([[ 1900., 30000.,  4000., 48300.],
       [ 1901., 47200.,  6100., 48200.],
       [ 1902., 70200.,  9800., 41500.],
       [ 1903., 77400., 35200., 38200.],
       [ 1904., 36300., 59400., 40600.],
       [ 1905., 20600., 41700., 39800.],
       [ 1906., 18100., 19000., 38600.],
       [ 1907., 21400., 13000., 42300.],
       [ 1908., 22000.,  8300., 44500.],
       [ 1909., 25400.,  9100., 42100.],
       [ 1910., 27100.,  7400., 46000.],
       [ 1911., 40300.,  8000., 46800.],
       [ 1912., 57000., 12300., 43800.],
       [ 1913., 76600., 19500., 40900.],
       [ 1914., 52300., 45700., 39400.],
       [ 1915., 19500., 51100., 39000.],
       [ 1916., 11200., 29700., 36700.],
       [ 1917.,  7600., 15800., 41800.],
       [ 1918., 14600.,  9700., 43300.],
       [ 1919., 16200., 10100., 41300.],
       [ 1920., 24700.,  8600., 47300.]])

In [17]:
year, hares, lynxes, carrots = data.T  #Columns to variables

In [18]:
print(year)

[1900. 1901. 1902. 1903. 1904. 1905. 1906. 1907. 1908. 1909. 1910. 1911.
 1912. 1913. 1914. 1915. 1916. 1917. 1918. 1919. 1920.]


In [19]:
#The mean population over time
population =data[:,1:]  #Consideration from second to last column
population

array([[30000.,  4000., 48300.],
       [47200.,  6100., 48200.],
       [70200.,  9800., 41500.],
       [77400., 35200., 38200.],
       [36300., 59400., 40600.],
       [20600., 41700., 39800.],
       [18100., 19000., 38600.],
       [21400., 13000., 42300.],
       [22000.,  8300., 44500.],
       [25400.,  9100., 42100.],
       [27100.,  7400., 46000.],
       [40300.,  8000., 46800.],
       [57000., 12300., 43800.],
       [76600., 19500., 40900.],
       [52300., 45700., 39400.],
       [19500., 51100., 39000.],
       [11200., 29700., 36700.],
       [ 7600., 15800., 41800.],
       [14600.,  9700., 43300.],
       [16200., 10100., 41300.],
       [24700.,  8600., 47300.]])

In [ ]:
#standered deviation along with column

In [20]:
population.std(axis=0)

array([20897.90645809, 16254.59153691,  3322.50622558])

In [21]:
#Which species has the highest population each year
np.argmax(population, axis=1)  #perform operation according to row

array([2, 2, 0, 0, 1, 1, 2, 2, 2, 2, 2, 2, 0, 0, 0, 1, 2, 2, 2, 2, 2],
      dtype=int64)

In [25]:
a=np.arange(0,40,10)
a

array([ 0, 10, 20, 30])

In [28]:
a=np.tile(np.arange(0,40,10),(3,1)) #3 times row-wise 1 time column wise
print(a)

[[ 0 10 20 30]
 [ 0 10 20 30]
 [ 0 10 20 30]]


In [30]:
x=np.tile(np.arange(0,40,10),(3,2)) #3 times row-wise 1 time column wise
print(x)

[[ 0 10 20 30  0 10 20 30]
 [ 0 10 20 30  0 10 20 30]
 [ 0 10 20 30  0 10 20 30]]


In [31]:
x=x.T
x

array([[ 0,  0,  0],
       [10, 10, 10],
       [20, 20, 20],
       [30, 30, 30],
       [ 0,  0,  0],
       [10, 10, 10],
       [20, 20, 20],
       [30, 30, 30]])

In [32]:
a=a.T
print(a)

[[ 0 10 20 30]
 [ 0 10 20 30]
 [ 0 10 20 30]]


In [33]:
b=np.array([0,1,2])
b

array([0, 1, 2])

In [34]:
 a+b #It will give you error

ValueError: operands could not be broadcast together with shapes (3,4) (3,) 

In [36]:
#1-D array
a=np.arange(0,40,10)
a.shape

(4,)

In [37]:
a=a[:,np.newaxis] # adds a new axis --> 2D array
a.shape

(4, 1)

In [38]:
a

array([[ 0],
       [10],
       [20],
       [30]])

In [39]:
a+b

array([[ 0,  1,  2],
       [10, 11, 12],
       [20, 21, 22],
       [30, 31, 32]])

In [45]:
#Flattening
a=np.array([[1,2,3],[4,5,6]]) #Convert it into 1-D array
a.ravel()

array([1, 2, 3, 4, 5, 6])

In [44]:
a=a.T
a.ravel()

array([1, 4, 2, 5, 3, 6])

In [47]:
#Reshaping-The Inverse operation to flatting
a=np.array([[1,2,3],[4,5,6]])
b=a.ravel()  #Here we saving the output of this in a variable.
b

array([1, 2, 3, 4, 5, 6])

In [49]:
b=b.reshape(2,3)
b

array([[1, 2, 3],
       [4, 5, 6]])

In [50]:
b[0,0]=500
b

array([[500,   2,   3],
       [  4,   5,   6]])

In [52]:
a #same result because they share same memory location

array([[500,   2,   3],
       [  4,   5,   6]])

In [53]:
#Note and Beware : Reshape may also return a copy
a=np.zeros((3,2))
a

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [54]:
a.T

array([[0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
a.T.reshape